### ISSUE TITLE
[FEATURE] requirements.txt

### ISSUE THREAD

**Issue by clach04** [parazeeknova/nyxtext#9]
# Nyx Text Feature Request

## Description

Provide requirements.txt

## Problem Statement

Easier to install, easier to pin versions if required

## Proposed Solution

Provide requirements.txt

## Use Cases

Installation

## Implementation Ideas

See PR https://github.com/parazeeknova/nyxtext/pull/10

## Alternatives Considered
[If you've considered alternative solutions to the problem, please describe them here and explain why you believe the proposed feature is the best approach.]

## Additional Context
[Add any other context or information that might be relevant to this feature request.]

## Your GitHub Username
[Please provide your GitHub username if you'd like to be credited for this feature request or if you'd like to be notified about updates.]

## Labels
[Choose appropriate labels to categorize the feature request, such as "enhancement", "new feature", etc.]

**Comment by parazeeknova** [comment]
Thanks, merged :)
